services:
  - type: web
    name: shl-recommender
    runtime: python
    pythonVersion: "3.11.6"
    plan: free
    rootDir: shl-recommender
    buildCommand: "pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true